### ISSUE TITLE
"passiert etwas sinnvolles?"

### ISSUE THREAD

**Issue by jwaldmann** [jvoigtlaender/Elm-Tutorium#2]
Sinn liegt im Auge des Betrachters. (Oder dessen, der die Spezifikation kennt ...)

Da es hier als Testfall gedacht ist (zur Beantwortung der Frage "habe ich Elm richtig installiert"), würde ich doch genauer beschreiben, welches die erwartete Beobachtung ist.

**Comment by jvoigtlaender** [comment]
addressed by https://github.com/jvoigtlaender/Elm-Tutorium/commit/05d10051cb6db93385001ce7249e218f1e69b9a0
